#!/bin/bash
GLOBIGNORE=*.mov

if [ -n "$1" ] ; then
	echo "$1"
	 #ffmpeg -y -hwaccel cuda -i "$1" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0     -f mov "${1%.*}.mov"
     ffmpeg -y -i "$1" -codec copy -f mov "${1%.}.mov"
	exit 0
fi

for i in *;do
	#ffmpeg -y -hwaccel cuda -i "$i" -vcodec mjpeg -q:v 2 -acodec pcm_s16be -q:a 0 -f mov "${i%.*}.mov"
    # ffmpeg -y -i "$i" -codec copy -f mov "${i%.}.mov"
    ffmpeg -y -i "$i" -c:v dnxhd -profile:v dnxhr_hq -pix_fmt yuv422p -c:a pcm_s16le -f mov "${i%.*}.mov"
#ffmpeg -y -i "$i" -vcodec dnxhd -acodec pcm_s16le -pix_fmt yuv422p -f mov "${i%mp4}.mov"

done

