#!/bin/sh

function z() {
    file=$1
    projects_path="$HOME/Documents/Projects"

    case $file in
        l) cd "$HOME/Documents/Latex"; ;;

        v) cd "$HOME/Documents/Projects/pullman"; ;;

        w) cd "$HOME/Documents/Projects/Horizon/src/web/WebHorizon"; ;;

        pg) cd "$HkME"/Documents/psg_project/learning ;;

        7) cd "$HOME/Documents/Projects/quany7a/"; ;;

        7a) cd "$HOME/Documents/Projects/quany7a/api/"; ;;

        a) cd "$HOME/Documents/Projects/pullman/Server/api/"; ;;

        n) cd "$HOME/.local/src/neovim"; ;;

        eb) cd "$HOME/Documents/ebooks/" ;;

        go) cd "$HOME/Documents/go_projects/" ;;

        s) cd "$HOME/.scripts/"
    esac
}
