#!/bin/sh
rfkill unblock bluetooth
bluetoothctl --timeout 1 scan on
dev=$(bluetoothctl devices | sed -n -e 's/^Device //p' | dmenu -l 30 | grep -Eo '^[^ ]+')

bluetoothctl connect $dev && {
	notify-send "Connect to $dev successfully!" &
	exit
} 

notify-send "Connect to $dev failed!" &
