#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via dmenu from emoji file.
icon_tmp=/tmp/icon_tmp
[ ! -f $icon_tmp ] && cut -d ';' -f1 ~/.local/share/larbs/emoji >$icon_tmp 
chosen=$(cat $icon_tmp | dmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
chosen="${chosen%\n*}"
if [ -n "$1" ]; then
	xdotool type "$chosen"
else
	echo "$chosen" | xclip -selection clipboard
	notify-send "'$chosen' copied to clipboard." &
fi
