#!/bin/sh
# tmux split-window -v -p 30
# tmux split-window -h -p 60
# tmux split-window -h -p 50
if [  -z "$TMUX" ]; then
    tmux new-session \; split-window -v -p 30 \; split-window -h -p 68 \; split-window -h -p 50\; select-pane -t 1
else
    tmux split-window -v -p 30 \; split-window -h -p 68 \; split-window -h -p 50\; select-pane -t 1
fi
